#!/usr/bin/env zsh

# general
alias c='clear'

# ls
alias ls="ls -hFN --color=auto --group-directories-first --hyperlink=auto"
alias la="ls -hFN --color=auto --group-directories-first --hyperlink=auto -a"
alias ll="ls -hFN --color=auto --group-directories-first --hyperlink=auto -l"

# Blender
#alias blender='/Applications/Blender.app/Contents/MacOS/blender'

# newvim
#alias vim='nvim'
# command -v nvim >/dev/null && alias vim="nvim" vi="nvim" v="nvim" vimdiff="nvim -d"
#alias vim='~/nvim.appimage'
alias vim='/snap/bin/nvim'


# kitty
alias icat="kitty +kitten icat"
[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

# pbcopy
alias pbcopy='xsel --clipboard --input'
