#!/usr/bin/env zsh

# fix typo
setopt correct

# history settings
setopt share_history
HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=50000

# ssh forwarding
ssh-add ~/.ssh/github

# cd + ls
function chpwd() { ls }
