#!/usr/bin/env zsh

# Ruby
eval "$(rbenv init -)"

# Python
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


