#!/usr/bin/env zsh

# Python
# export PYENV_ROOT="$HOME/.pyenv"
export PYENV_ROOT="/research/tamura_research/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv shell --unset

# pyenv
export PYENV_VIRTUALENV_DISABLE_PROMPT=1   # disable pyenv-virtualenv prompt

# nvm
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# zim
#eval "$(lua /path/to/z.lua --init zsh)"
